language: scala
scala:
  - 2.10.4
branches:
  only:
    - master
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test
notifications:
  email:
    recipients:
      - joao.l.v.vasques@gmail.com
jdk:
  - oraclejdk8
  